window.stolpersteine.popupTexts = {
  about: {
    title: 'Über diese Seite',
    text: [
      '<h2>Wer?</h2>',
      '<p>',
      'Mein Name ist Josef Schugt. Ich arbeite bei einer Meckenheimer Firma, die Software im Bereich ',
      '<a target="_blank" href="https://de.wikipedia.org/wiki/Geoinformationssystem">Geoinformationssysteme</a> ',
      'entwickelt. Diese Seite ist in meiner Freizeit entstanden.',
      '</p>',
      '<h2>Was?</h2>',
      '<p>',
      'Diese Seite visualisiert die Orte in Bonn, an denen der Künstler Gunter Demnig im Rahmen seines ',
      'Kunstprojekts <em>Stolpersteine. Ein Kunstprojekt für Europa.</em> Gedenksteine verlegt hat, die an Opfer ',
      'der NS-Gräuel erinnern. Das Projekt gedenkt mit zehntausenden, in Belarus (Weißrussland), Belgien, ',
      'Frankreich, Griechenland, Italien, Kroatien, Litauen, Luxemburg, den Niederlanden, Norwegen, Österreich, ',
      'Polen, der Russischen Förderation, Rumänien, der Schweiz, der Slowakei, Slowenien, Spanien, Tschechien, der ',
      'Ukraine, Ungarn und natürlich auch Deutschland zu findenden Denkmälern einer grausam großen Zahl von ',
      'Einzelschicksalen. Schon ihre Zahl sprengt alles, was man gefühlsmäßig noch erfassen kann. Und dabei sind ',
      'die Denkmäler nur Schlaglichter, die einen kleinen Bruchteil der NS-Verbrechen beleuchten.',
      '</p>',
      '<h2>Warum?</h2>',
      '<p>',
      'Es gab für mich eine Reihe von Beweggründen, diese Seite ins Leben zu rufen. Der wichtigste Grund liegt in ',
      'meiner Kindheit. Meine Großmutter erzählte davon, dass in direkter Nachbarschaft der jüdische Metzger Josef ',
      'Levy schon lange vor der Reichskristallnacht von Nazis umgebracht wurde. Heute weiß ich, dass sich am ',
      'Nachmittag des 18. Juni <strong>1935</strong> vor seinem Geschäft ein größerer Trupp SA-Männer ',
      'zusammengerottet hat und er am nächsten Tag im Sterben liegend gefunden wurde. Als meine Großmutter mir das ',
      'in meiner Kindheit erzählte, lebten noch Täter. Unbehelligt. Weil die Zeugen auch Jahrzente später noch ',
      'Angst vor den damaligen Tätern hatten. Heute leben die Täter nicht mehr &ndash; das kann man als Segen ',
      'sehen, aber auch als furchtbare Ungerechtigtkeit, da sie nie bestraft wurden.',
      '</p>',
      '<p>',
      'Der letztliche Auslöser, diese Seite ins Leben zu rufen, war meine Erkenntnis, dass eine einfache Karte ',
      'prinzipiell ungeeignet ist, Stolpersteine darzustellen. Das liegt daran, dass sie häufig in Gruppen ',
      'vorkommen, weil ganze Familien ermordet wurden. Sie liegen dann so eng beieinander, dass auf einer Karte ',
      'bei jedem sinnvollen Maßstab unvermeidlicherweise höchsten ein einziger davon zu sehen ist.',
      '</p>',
      '<p>',
      'Mir reichte es nicht, nur zu markieren, wo sich Stolpersteine befinden. Mir war es wichtig, dass online ',
      'mindestens die Informationen zugänglich sind, die auch vor Ort vorhanden sind. Dazu gehört ',
      'selbstverständlich die Inschrift. Aber nicht nur. Die Information, ob es sich um einen isolierten ',
      'Stolperstein handelt oder ob in seiner Nähe an weitere Opfer erinnert wird, ist in meinen Augen fast ',
      'genauso wichtig. Sie trägt ganz wesentlich zur Wahrnehmung bei, wie unterschiedlich die Lebenssituationen ',
      'der Opfer waren.',
      '</p>',
      '<p>',
      'Ein weiterer Aspekt war, dass ich das Virtuelle mit dem Physischen verbinden wollte. Ein wesentlicher ',
      'Aspekt dieses Projekts war und ist es daher, die Stolpersteine so wie sie sich in der Realität präsentieren ',
      'mit Fotos zu dokumentieren. Dabei ist es mir wichtig, dass die Fotos nicht nur den Stolperstein zeigen, ',
      'sondern auch, wie er sich in seine Umgebung einfügt. Der Kompromiss zwischen der Darstellung der Umgebung ',
      'und der Erkennbarkeit des Textes des einzelnen Stolpersteins fiel mir dabei nicht immer leicht. Nicht alle ',
      'Fotos genügen diesem Anspruch, denn ich habe nicht alle der gezeigten Stolpersteine persönlich fotografiert.',
      '</p>'
    ].join('\n')
  },
  copyright: {
    title: 'Urheberrechtliches',
    text: [
      '<h2>Software</h2>',
      '<p>',
      'Die hier verwendete Software ist Open Source und ',
      '<a target="_blank" href="https://github.com/penpendede/stolperstein-bonn">',
      'kann auf GitHub eingesehen werden</a>. Dort finden Sie die Lizenz der eigentlichen Software wie auch die ',
      'Lizenzen der verwendeten Bibliotheken und Hilfsprogramme.',
      '</p>',
      '<h2>Stolpersteine</h2>',
      '<p>',
      'Die Daten der Stolpersteine werden mit Hilfe der <a href="https://overpass-turbo.eu">Overpass-API</a> direkt ',
      'aus der Datenbank von <a target="_blank" href="http://osm.org/">OpenStreetMap</a> entnommen.',
      '</p>',
      '<p>',
      'Für die Daten von OpenStreetMap gilt die ',
      '<a target="_blank" href="https://opendatacommons.org/licenses/odbl/1-0/">Open Database License (ODbL) v1.0</a>',
      '</p>',
      '<h2>Fotos</h2>',
      '<p>',
      'Die Internetaddressen der angezeigten Fotos werden den von OpenStreetMap gelieferten Daten entnommen. Zu den ',
      'Lizenzen der einzelnen Fotos klicken Sie bitte auf das jeweilige Foto; Sie werden dann - sofern möglich ',
      '&ndash; zur entsprechenden Internetseite bei ',
      '<a target="_blank" href="https://commons.wikimedia.org/">Wikimedia Commons</a> weitergeleitet.',
      '</p>',
      '<h2>Grenzen der Stadt, Stadtbezirke und Ortsteile</h2>',
      '<p>',
      'Die verwendeten Informationen sind von der Stadt Bonn als OpenData der Allgemeinheit zur Verfügung gestellt ',
      'worden.',
      '</p>',
      '<ul>',
      '<li>',
      'Lizenz: ',
      '<a target="_blank" href="https://creativecommons.org/publicdomain/zero/1.0/">',
      'creativecommons.org/publicdomain/zero/1.0/',
      '</a>',
      '</li>',
      '<li>',
      'Ortsteile: ',
      '<a target="_blank" href="https://opendata.bonn.de/dataset/fl%C3%A4chen-der-ortsteile">',
      'opendata.bonn.de/dataset/flächen-der-ortsteile',
      '</a>',
      '</li>',
      '<li>',
      'Stadtbezirke: ',
      '<a target="_blank" href="https://opendata.bonn.de/dataset/fl%C3%A4chen-der-stadtbezirke">',
      'opendata.bonn.de/dataset/flächen-der-stadtbezirke',
      '</a>',
      '</li>',
      '<li>',
      'Stadt: ',
      '<a target="_blank" href="https://opendata.bonn.de/dataset/fl%C3%A4che-stadtgebiet-bonn">',
      'opendata.bonn.de/dataset/fläche-stadtgebiet-bonn',
      '</a>',
      '</li>',
      '</ul>'
    ].join('\n')
  },
  filter: {
    title: 'Stolpersteine auswählen',
    text: [
      '<form style="margin-top: 0;">',
      '<p style="margin-top: 0;"><b>Name des NS-Opfers</b></p>',
      '<input type="text" name="name" id="name" onkeyup="window.stolpersteine.fn.updateFilter()" ',
      'onpaste="window.stolpersteine.fn.updateFilter()">',
      '<p><b>Inschrift</b></p>',
      '<input type="text" name="memorialText" id="memorialText" onkeyup="window.stolpersteine.fn.updateFilter()" ',
      'onpaste="window.stolpersteine.fn.updateFilter()">',
      '<p onclick="e=document.getElementById(\'additionalFilterSwitcher\');e.checked = !e.checked">',
      '<b class="pseudolink" title="Diese Filter sind vorwiegend für die Pflege der OSM-Datenbank nützlich">Weitere Filter ein/ausblenden</b>',
      '</p>',
      '<input type="checkbox" class="displaySwitcher" id="additionalFilterSwitcher">',
      '<div>',
      '<p><b>Attribut "image"</b></p>',
      '<div class="half">',
      '<input type="checkbox" name="withImage" id="withImage" checked',
      'onchange="window.stolpersteine.fn.updateFilter()"> mit',
      '</div>',
      '<div class="half">',
      '<input type="checkbox" name="withoutImage" id="withoutImage" checked',
      'onchange="window.stolpersteine.fn.updateFilter()"> ohne',
      '</div>',
      '<p><b>Attribut "memorial:addr"</b></p>',
      '<div class="half">',
      '<input type="checkbox" name="withMemorialAddr" id="withMemorialAddr" checked',
      'onchange="window.stolpersteine.fn.updateFilter()"> mit',
      '</div>',
      '<div class="half">',
      '<input type="checkbox" name="withoutMemorialAddr" id="withoutMemorialAddr" checked',
      'onchange="window.stolpersteine.fn.updateFilter()"> ohne',
      '</div>',
      '<p><b>Attribut-Gruppe "addr:"</b></p>',
      '<div class="half">',
      '<input type="checkbox" name="withAddr" id="withAddr" checked',
      'onchange="window.stolpersteine.fn.updateFilter()"> mit',
      '</div>',
      '<div class="half">',
      '<input type="checkbox" name="withoutAddr" id="withoutAddr" checked',
      'onchange="window.stolpersteine.fn.updateFilter()"> ohne',
      '</div>',
      '<p><b>Attribut-Gruppe "object:"</b></p>',
      '<div class="half">',
      '<input type="checkbox" name="withObject" id="withObject" checked',
      'onchange="window.stolpersteine.fn.updateFilter()"> mit',
      '</div>',
      '<div class="half">',
      '<input type="checkbox" name="withoutObject" id="withoutObject" checked',
      'onchange="window.stolpersteine.fn.updateFilter()"> ohne',
      '</div>',
      '</div>',
      '</form>'
    ].join('\n')
  },
  links: {
    title: 'Links',
    text: [
      '<p>',
      'Es gibt sehr viele Informationsquellen, ich möchte nur einige wenige nennen',
      '</p>',
      '<ul>',
      '<li>',
      '<a target="_blank" href="https://www.bundesarchiv.de/gedenkbuch/">',
      'Gedenkbuch - Opfer der Verfolgung der Juden unter der nationalsozialistischen Gewaltherrschaft in ',
      'Deutschland 1933-1945',
      '</a>',
      '</li>',
      '<li>',
      '<a target="_blank" href="http://www.ns-gedenkstaetten.de/nrw/bonn/besucherinformationen.html">',
      'Gedenkstätte für die Bonner Opfer des Nationalsozialismus - An der Synagoge e.V. </a> (leider immer noch ',
      'unverschlüsselt). ',
      '</li>',
      '<li>',
      '<a target="_blank" href="http://stolpersteine.eu">Stolpersteine.EU</a> (leider immer noch unverschlüsselt).',
      '</li>',
      '<li>',
      '<a target="_blank" href="https://www.ushmm.org/">United States Holocaust Memorial Museum</a>',
      '</li>',
      '<li>',
      '<a target="_blank" href="https://www.yadvashem.org/de.html">',
      'Yad Vashem - Die Behörde zum Gedenken an die Märtyrer und Helden des Holocaust',
      '</a>',
      '</li>',
      '</ul>'
    ].join('\n')
  },
  stolpersteine: {
    title: 'Stolpersteine',
    text: [
      '<p>',
      '<strong>Stolpersteine. Ein Kunstprojekt für Europa.</strong> ist der Name eines Projekt des Künstlers Gunter ',
      'Demnig. Mit im Boden verlegten kleinen Gedenktafeln soll an das Schicksal der Menschen erinnert werden, die ',
      'in der Zeit des Nationalsozialismus verfolgt, ermordet, deportiert, vertrieben oder in den Suizid getrieben ',
      'wurden.',
      '</p>',
      '<p>',
      'Diese quadratischen Messingtafeln mit abgerundeten Ecken und Kanten sind mit von Hand eingeschlagenen Lettern ',
      'beschriftet und werden von einem angegossenen Betonwürfel mit einer Kantenlänge von 96&nbsp;mm und einer Höhe ',
      'von 100&nbsp;mm getragen. Sie werden meist vor den letzten frei gewählten Wohnhäusern der NS-Opfer ',
      'niveaugleich in das Pflaster bzw. den Belag des jeweiligen Gehwegs eingelassen. Die Stolpersteine sind das ',
      'größte dezentrale Mahnmal der Welt.',
      '</p>',
      '<p>',
      'Für weitere Informationen zu den Stolpersteinen empfehle ich den',
      '<a target="_blank" href="https://de.wikipedia.org/wiki/Stolpersteine">sehr guten Wikipediaartikel.</a>',
      '</p>'
    ].join('\n')
  },
  impressum: {
    title: 'Impressum',
    text: [
      '<p>',
      'Josef Schugt<br>',
      'Drachenburgstraße 42<br>',
      '53179 Bonn',
      '</p>',
      '<p>',
      '<span>penpendede</span><span>&#64;</span><span>mail</span><span>&#46;</span><span>ru</span>',
      '</p>',
      '<p>',
      '<span>T</span><span>e</span><span>l</span>',
      '<span>&#43;</span><span>49</span><span>1</span><span>&#55;</span><span>5</span><span>67</span><span>60</span><span>70</span><span>1',
      '</p>'
    ].join('\n')
  },
  datenschutz: {
    title: 'Datenschutzerklärung',
    text: [
      '<h3>Allgemeiner Hinweis und Pflichtinformationen</h3>',
      '<h4>Benennung der verantwortlichen Stelle</h4>',
      '<p>',
      'Die verantwortliche Stelle für die Datenverarbeitung auf dieser Website ist:',
      '</p>',
      '<p>',
      'Josef Schugt<br>',
      'Drachenburgstraße 42<br>',
      '53179 Bonn',
      '</p>',
      '<p>',
      'Die verantwortliche Stelle entscheidet allein oder gemeinsam mit anderen über die Zwecke und Mittel der ',
      'Verarbeitung von personenbezogenen Daten (z.B. Namen, Kontaktdaten o. Ä.).',
      '</p>',
      '<h4>Widerruf Ihrer Einwilligung zur Datenverarbeitung</h4>',
      '<p>',
      'Nur mit Ihrer ausdrücklichen Einwilligung sind einige Vorgänge der Datenverarbeitung möglich. Ein Widerruf ',
      'Ihrer bereits erteilten Einwilligung ist jederzeit möglich. Für den Widerruf genügt eine formlose ',
      'Mitteilung per E-Mail. Die Rechtmäßigkeit der bis zum Widerruf erfolgten Datenverarbeitung bleibt vom ',
      'Widerruf unberührt.',
      '</p>',
      '<h4>Recht auf Beschwerde bei der zuständigen Aufsichtsbehörde</h4>',
      '<p>',
      'Als Betroffener steht Ihnen im Falle eines datenschutzrechtlichen Verstoßes ein Beschwerderecht bei der ',
      'zuständigen Aufsichtsbehörde zu. Zuständige Aufsichtsbehörde bezüglich datenschutzrechtlicher Fragen ist ',
      'der Landesdatenschutzbeauftragte des Bundeslandes, in dem sich der Sitz unseres Unternehmens befindet. Der ',
      'folgende Link stellt eine Liste der Datenschutzbeauftragten sowie deren Kontaktdaten bereit: ',
      '<a href="https://www.bfdi.bund.de/DE/Infothek/Anschriften_Links/anschriften_links-node.html" ',
      'target="_blank">https://www.bfdi.bund.de/DE/Infothek/Anschriften_Links/anschriften_links-node.html</a>.',
      '</p>',
      '<h3>Recht auf Datenübertragbarkeit</h3>',
      '<p>',
      'Ihnen steht das Recht zu, Daten, die wir auf Grundlage Ihrer Einwilligung oder in Erfüllung eines Vertrags ',
      'automatisiert verarbeiten, an sich oder an Dritte aushändigen zu lassen. Die Bereitstellung erfolgt in ',
      'einem maschinenlesbaren Format. Sofern Sie die direkte Übertragung der Daten an einen anderen ',
      'Verantwortlichen verlangen, erfolgt dies nur, soweit es technisch machbar ist.',
      '</p>',
      '<h3>Recht auf Auskunft, Berichtigung, Sperrung, Löschung</h3>',
      '<p>',
      'Sie haben jederzeit im Rahmen der geltenden gesetzlichen Bestimmungen das Recht auf unentgeltliche Auskunft ',
      'über Ihre gespeicherten personenbezogenen Daten, Herkunft der Daten, deren Empfänger und den Zweck der ',
      'Datenverarbeitung und ggf. ein Recht auf Berichtigung, Sperrung oder Löschung dieser Daten. Diesbezüglich ',
      'und auch zu weiteren Fragen zum Thema personenbezogene Daten können Sie sich jederzeit über die im',
      'Impressum aufgeführten Kontaktmöglichkeiten an uns wenden.',
      '</p>',
      '<h3>SSL- bzw. TLS-Verschlüsselung</h3>',
      '<p>Aus Sicherheitsgründen und zum Schutz der Übertragung vertraulicher Inhalte, die Sie an uns als ',
      'Seitenbetreiber senden, nutzt unsere Website eine SSL-bzw. TLS-Verschlüsselung. Damit sind Daten, die Sie ',
      'über diese Website übermitteln, für Dritte nicht mitlesbar. Sie erkennen eine verschlüsselte Verbindung an',
      'der »https://« Adresszeile Ihres Browsers und am Schloss-Symbol in der Browserzeile.',
      '</p>',
      '<h3>Server-Log-Dateien</h3>',
      '<p>',
      'In Server-Log-Dateien erhebt und speichert der Provider der Website automatisch Informationen, die Ihr ',
      'Browser automatisch an uns übermittelt. Dies sind:',
      '</p>',
      '<ul>',
      '<li>Besuchte Seite auf unserer Domain</li>',
      '<li>Datum und Uhrzeit der Serveranfrage</li>',
      '<li>Browsertyp und Browserversion</li>',
      '<li>Verwendetes Betriebssystem</li>',
      '<li>Referrer URL</li>',
      '<li>Hostname des zugreifenden Rechners</li>',
      '<li>IP-Adresse</li>',
      '</ul>',
      '<p>',
      'Es findet keine Zusammenführung dieser Daten mit anderen Datenquellen statt. Grundlage der ',
      'Datenverarbeitung bildet Artikel 6 Absatz 1 Buchstabe b DSGVO, der die Verarbeitung von Daten zur Erfüllung ',
      'eines Vertrags oder vorvertraglicher Maßnahmen gestattet.',
      '</p>',
      '<p>',
      '<small>Quelle: Datenschutz-Konfigurator von <a href="http://www.mein-datenschutzbeauftragter.de" ',
      'target="_blank">mein-datenschutzbeauftragter.de</a></small>',
      '</p>'
    ].join('\n')
  }
}
