window.stolpersteine.popupTexts = {
  about: [
    '<h1>Über diese Seite</h1>',
    '<h2>Wer?</h2>',
    '<p>',
    'Mein Name ist Josef Schugt. Ich arbeite bei einer Meckenheimer Firma, die Software im Bereich ',
    '<a href="https://de.wikipedia.org/wiki/Geoinformationssystem">Geoinformationssysteme</a> entwickelt. Diese ',
    'Seite ist in meiner Freizeit entstanden.',
    '</p>',
    '<h2>Was?</h2>',
    '<p>',
    'Diese Seite visualisiert die Orte in Bonn, an denen der Künstler Gunter Demnig im Rahmen seines ',
    'Kunstprojekts <em>Stolpersteine. Ein Kunstprojekt für Europa.</em> Gedenksteine verlegt hat, die an Opfer ',
    'der NS-Gräuel erinnern. Das Projekt gedenkt mit zehntausenden, in Belarus (Weißrussland), Belgien, ',
    'Frankreich, Griechenland, Italien, Kroatien, Litauen, Luxemburg, den Niederlanden, Norwegen, Österreich, ',
    'Polen, der Russischen Förderation, Rumänien, der Schweiz, der Slowakei, Slowenien, Spanien, Tschechien, der ',
    'Ukraine, Ungarn und natürlich auch Deutschland zu findenden Denkmälern einer grausam großen Zahl von ',
    'Einzelschicksalen. Schon ihre Zahl sprengt alles, was man gefühlsmäßig noch erfassen kann. Und dabei sind ',
    'die Denkmäler nur Schlaglichter, die einen kleinen Bruchteil der NS-Verbrechen beleuchten.',
    '</p>',
    '<h2>Warum?</h2>',
    '<p>',
    'Es gab für mich eine Reihe von Beweggründen, diese Seite ins Leben zu rufen. Der wichtigste Grund liegt in ',
    'meiner Kindheit. Meine Großmutter erzählte davon, dass in direkter Nachbarschaft der jüdische Metzger Josef ',
    'Levy schon lange vor der Reichskristallnacht von Nazis umgebracht wurde. Heute weiß ich, dass sich am ',
    'Nachmittag des 18. Juni <strong>1935</strong> vor seinem Geschäft ein größerer Trupp SA-Männer ',
    'zusammengerottet hat und er am nächsten Tag im Sterben liegend gefunden wurde. Als meine Großmutter mir das ',
    'in meiner Kindheit erzählte, lebten noch Täter. Unbehelligt. Weil die Zeugen auch Jahrzente später noch ',
    'Angst vor den damaligen Tätern hatten. Heute leben die Täter nicht mehr &ndash; das kann man als Segen ',
    'sehen, aber auch als furchtbare Ungerechtigtkeit, da sie nie bestraft wurden.',
    '</p>',
    '<p>',
    'Der letztliche Auslöser, diese Seite ins Leben zu rufen, war meine Erkenntnis, dass eine einfache Karte ',
    'prinzipiell ungeeignet ist, Stolpersteine darzustellen. Das liegt daran, dass sie häufig in Gruppen ',
    'vorkommen, weil ganze Familien ermordet wurden. Sie liegen dann so eng beieinander, dass auf einer Karte ',
    'bei jedem sinnvollen Maßstab unvermeidlicherweise höchsten ein einziger davon zu sehen ist.',
    '</p>',
    '<p>',
    'Mir reichte es nicht, nur zu markieren, wo sich Stolpersteine befinden. Mir war es wichtig, dass online ',
    'mindestens die Informationen zugänglich sind, die auch vor Ort vorhanden sind. Dazu gehört ',
    'selbstverständlich die Inschrift. Aber nicht nur. Die Information, ob es sich um einen isolierten ',
    'Stolperstein handelt oder ob in seiner Nähe an weitere Opfer erinnert wird, ist in meinen Augen fast ',
    'genauso wichtig. Sie trägt ganz wesentlich zur Wahrnehmung bei, wie unterschiedlich die Lebenssituationen ',
    'der Opfer waren.',
    '</p>',
    '<p>',
    'Ein weiterer Aspekt war, dass ich das Virtuelle mit dem Physischen verbinden wollte. Ein wesentlicher ',
    'Aspekt dieses Projekts war und ist es daher, die Stolpersteine so wie sie sich in der Realität präsentieren ',
    'mit Fotos zu dokumentieren. Dabei ist es mir wichtig, dass die Fotos nicht nur den Stolperstein zeigen, ',
    'sondern auch, wie er sich in seine Umgebung einfügt. Der Kompromiss zwischen der Darstellung der Umgebung ',
    'und der Erkennbarkeit des Textes des einzelnen Stolpersteins fiel mir dabei nicht immer leicht. Nicht alle ',
    'Fotos genügen diesem Anspruch, denn ich habe nicht alle der gezeigten Stolpersteine persönlich fotografiert.',
    '</p>'
  ].join(),
  copyright: [
    '<h1>Urheberrechtliches</h1>',
    '<h2>Software</h2>',
    '<p>',
    'Die hier verwendete Software ist Open Source und ',
    '<a href="https://github.com/penpendede/stolperstein-bonn">kann auf GitHub eingesehen werden</a>. Dort finden ',
    'Sie die Lizenz der eigentlichen Software wie auch die Lizenzen der verwendeten Bibliotheken und Hilfsprogramme.',
    '</p>',
    '<h2>Stolpersteine</h2>',
    '<p>',
    'Die Daten der Stolpersteine werden mit Hilfe der <a href="https://overpass-turbo.eu">Overpass-API</a> direkt ',
    'aus der Datenbank von <a href="http://osm.org/">OpenStreetMap</a> entnommen.',
    '</p>',
    '<p>',
    'Für die Daten von OpenStreetMap gilt die ',
    '<a href="http://opendatacommons.org/licenses/odbl/1-0/">Open Database License (ODbL) v1.0</a>',
    '</p>',
    '<h2>Fotos</h2>',
    '<p>',
    'Die Internetaddressen der angezeigten Fotos werden den von OpenStreetMap gelieferten Daten entnommen. Zu den ',
    'Lizenzen der einzelnen Fotos klicken Sie bitte auf das jeweilige Foto; Sie werden dann - sofern möglich ',
    '&ndash; zur entsprechenden Internetseite bei <a href="https://commons.wikimedia.org/">"Wikimedia Commons</a> ',
    'weitergeleitet.',
    '</p>',
    '<h2>Grenzen der Stadt, Stadtbezirke und Ortsteile</h2>',
    '<p>',
    'Die verwendeten Informationen sind von der Stadt Bonn als OpenData der Allgemeinheit zur Verfügung gestellt ',
    'worden.',
    '</p>',
    '<ul>',
    '<li>',
    'Lizenz: ',
    '<a href="https://creativecommons.org/publicdomain/zero/1.0/">',
    'creativecommons.org/publicdomain/zero/1.0/',
    '</a>',
    '</li>',
    '<li>',
    'Ortsteile: ',
    '<a href="https://opendata.bonn.de/dataset/flächen-der-ortsteile">',
    'opendata.bonn.de/dataset/flächen-der-ortsteile',
    '</a>',
    '</li>',
    '<li>',
    'Stadtbezirke: ',
    '<a href="https://opendata.bonn.de/dataset/flächen-der-stadtbezirke">',
    'opendata.bonn.de/dataset/flächen-der-stadtbezirke',
    '</a>',
    '</li>',
    '<li>',
    'Stadt: ',
    '<a href="https://opendata.bonn.de/dataset/fläche-des-stadtgebiets">',
    'opendata.bonn.de/dataset/fläche-des-stadtgebiets',
    '</a>',
    '</li>',
    '</ul>'
  ].join(),
  links: [
    '<h1>Links</h1>',
    '<p>',
    'Es gibt sehr viele Informationsquellen, ich möchte nur einige wenige nennen',
    '</p>',
    '<ul>',
    '<li>',
    '<a href="https://www.bundesarchiv.de/gedenkbuch/">',
    'Gedenkbuch - Opfer der Verfolgung der Juden unter der nationalsozialistischen Gewaltherrschaft in ',
    'Deutschland 1933-1945',
    '</a>',
    '</li>',
    '<li>',
    '<a href="https://www.ns-gedenkstaetten.de/nrw/bonn/besucherinformationen.html">',
    'Gedenkstätte für die Bonner Opfer des Nationalsozialismus - An der Synagoge e.V.',
    '</a>',
    '</li>',
    '<li>',
    '<a href="http://stolpersteine.eu">Stolpersteine.EU</a>',
    '</li>',
    '<li>',
    '<a href="https://www.ushmm.org/">United States Holocaust Memorial Museum</a>',
    '</li>',
    '<li>',
    '<a href="http://www.yadvashem.org/yv/de/">',
    'Yad Vashem - Die Behörde zum Gedenken an die Märtyrer und Helden des Holocaust',
    '</a>',
    '</li>',
    '</ul>'
  ].join(),
  stolpersteine: [
    '<h1>Stolpersteine</h1>',
    '<p>',
    '<strong>Stolpersteine. Ein Kunstprojekt für Europa.</strong> ist der Name eines Projekt des Künstlers Gunter ',
    'Demnig. Mit im Boden verlegten kleinen Gedenktafeln soll an das Schicksal der Menschen erinnert werden, die ',
    'in der Zeit des Nationalsozialismus verfolgt, ermordet, deportiert, vertrieben oder in den Suizid getrieben ',
    'wurden.',
    '</p>',
    '<p>',
    'Diese quadratischen Messingtafeln mit abgerundeten Ecken und Kanten sind mit von Hand eingeschlagenen Lettern ',
    'beschriftet und werden von einem angegossenen Betonwürfel mit einer Kantenlänge von 96&nbsp;mm und einer Höhe ',
    'von 100&nbsp;mm getragen. Sie werden meist vor den letzten frei gewählten Wohnhäusern der NS-Opfer ',
    'niveaugleich in das Pflaster bzw. den Belag des jeweiligen Gehwegs eingelassen. Die Stolpersteine sind das ',
    'größte dezentrale Mahnmal der Welt.',
    '</p>',
    '<p>',
    'Für weitere Informationen zu den Stolpersteinen empfehle ich den',
    '<a href="https://de.wikipedia.org/wiki/Stolpersteine">sehr guten Wikipediaartikel.</a>',
    '</p>'
  ].join()
}
